# Generated by Django 3.1.4 on 2021-03-07 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('km', '0003_auto_20210228_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.TextField(max_length=150, null=True),
        ),
    ]
