# Generated by Django 3.1 on 2021-03-15 04:53

import django.core.validators
from django.db import migrations, models
import km.models


class Migration(migrations.Migration):

    dependencies = [
        ('km', '0004_auto_20210307_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='entry_year',
            field=models.IntegerField(choices=[(2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020)], default=2021, max_length=4, validators=[django.core.validators.MinValueValidator(2016), km.models.max_value_current_year], verbose_name='year'),
        ),
    ]
