# Generated by Django 3.1 on 2021-03-15 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('km', '0005_auto_20210315_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile-icon-png-898.png', null=True, upload_to=''),
        ),
    ]
