# Generated by Django 3.1 on 2021-03-20 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('km', '0006_auto_20210315_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='key',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
