# Generated by Django 3.1.4 on 2021-03-21 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('km', '0008_auto_20210320_1720'),
        ('km', '0008_auto_20210321_1724'),
    ]

    operations = [
    ]
