# Generated by Django 3.1 on 2021-05-10 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('km', '0014_auto_20210509_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
