# Generated by Django 3.1 on 2021-05-14 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('km', '0015_article_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='body',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='article',
            name='interviewee_name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='interviewee_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
