# Generated by Django 3.1 on 2021-05-15 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('km', '0018_remove_article_industry'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='industry',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
