# Generated by Django 3.1 on 2021-06-12 07:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('km', '0020_post_mentioned_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='like_user_list',
            field=models.ManyToManyField(blank=True, null=True, related_name='like_user_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
