# Generated by Django 3.1 on 2021-06-30 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('km', '0022_auto_20210612_1821'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['date_added']},
        ),
    ]
