# Generated by Django 3.1 on 2021-07-10 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('km', '0023_auto_20210630_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_reply_to',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='km.comment'),
        ),
    ]
