# Generated by Django 3.1 on 2021-07-17 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('km', '0025_auto_20210717_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='ordering_numbers',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
