# Generated by Django 3.1 on 2021-07-17 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('km', '0026_tag_ordering_numbers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['ordering_number']},
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='ordering_numbers',
            new_name='ordering_number',
        ),
    ]
