# Generated by Django 3.1.4 on 2021-08-14 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('km', '0027_auto_20210717_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniJobParentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='AlumniJobChildCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='km.alumnijobparentcategory', verbose_name='親カテゴリー')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='job_category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='km.alumnijobchildcategory', verbose_name='業界'),
        ),
    ]
