# Generated by Django 3.1.4 on 2021-08-20 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('km', '0028_auto_20210814_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='offered_job_category',
            field=models.ManyToManyField(blank=True, related_name='offered_job_category', to='km.AlumniJobChildCategory', verbose_name='内定獲得業界'),
        ),
    ]
