# Generated by Django 3.1.4 on 2021-08-21 01:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('km', '0029_customuser_offered_job_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='offered_job_category',
        ),
        migrations.CreateModel(
            name='OfferedJobJoinTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offered_job_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='km.alumnijobchildcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
