# Generated by Django 3.1.4 on 2021-08-21 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('km', '0030_auto_20210821_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offeredjobjointable',
            name='offered_job_category',
        ),
        migrations.AddField(
            model_name='offeredjobjointable',
            name='commited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offeredjobjointable',
            name='offered_job_child_category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='km.alumnijobchildcategory'),
        ),
        migrations.AddField(
            model_name='offeredjobjointable',
            name='offered_job_parent_category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='km.alumnijobparentcategory'),
        ),
    ]
