# Generated by Django 3.1.4 on 2021-08-21 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('km', '0031_auto_20210821_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offeredjobjointable',
            name='commited',
        ),
        migrations.AlterField(
            model_name='offeredjobjointable',
            name='offered_job_parent_category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='km.alumnijobparentcategory'),
        ),
    ]
