# Generated by Django 3.1.4 on 2021-09-02 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('km', '0032_auto_20210821_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='requested_industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='km.alumnijobchildcategory'),
        ),
    ]
