# Generated by Django 3.1.4 on 2021-10-10 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('km', '0034_post_requested_parent_industry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_public',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='name_is_shown',
            field=models.BooleanField(),
        ),
    ]
